{
 "title": "Sonda Temperatura CPD TR",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "DSB 1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hora de Brasilia",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "columns": [
      { "selector": "field1", "text": "Temperatura", "type": "number" }
     ],
     "evaltype": "0",
     "group": { "filter": "sondas" },
     "host": { "filter": "Sonda Temperatura CPD-TR" },
     "item": { "filter": "Temperatura" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "parser": "backend",
     "proxy": { "filter": "" },
     "root_selector": "feeds",
     "schema": 12,
     "source": "url",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1047093/feeds.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Temperatura Mínima",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "columns": [
      { "selector": "field2", "text": "Mínima", "type": "number" }
     ],
     "evaltype": "0",
     "group": { "filter": "sondas" },
     "host": { "filter": "Sonda Temperatura CPD-TR" },
     "item": { "filter": "Temperatura Minima" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "parser": "backend",
     "proxy": { "filter": "" },
     "root_selector": "feeds",
     "schema": 12,
     "source": "url",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1047093/feeds.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Temperatura Máxima",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "columns": [
      { "selector": "field3", "text": "Maxima", "type": "number" }
     ],
     "evaltype": "0",
     "group": { "filter": "sondas" },
     "host": { "filter": "Sonda Temperatura CPD-TR" },
     "item": { "filter": "Temperatura Maxima" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "parser": "backend",
     "proxy": { "filter": "" },
     "root_selector": "feeds",
     "schema": 12,
     "source": "url",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1047093/feeds.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Powered by Nextcon",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; font-size: 30px;\">DSB Monitor Zabbix</div>"
   }
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "columns": [
      { "selector": "last_created_at", "text": "", "type": "string" },
      { "selector": "status", "text": "", "type": "number" }
     ],
     "evaltype": "0",
     "group": { "filter": "sondas" },
     "host": { "filter": "Sonda Temperatura CPD-TR" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "parser": "backend",
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "source": "url",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "type": "json",
     "url": "http://195.35.17.162:5000/?time=7&channelid=1047093",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Nextcon",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "application": { "filter": "" },
     "columns": [
      { "selector": "created_at", "text": "Data", "timestampFormat": "", "type": "timestamp" },
      { "selector": "field1", "text": "Temperatura", "type": "number" }
     ],
     "evaltype": "0",
     "group": { "filter": "sondas" },
     "host": { "filter": "Sonda Temperatura CPD-TR" },
     "item": { "filter": "Temperatura" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "parser": "backend",
     "proxy": { "filter": "" },
     "root_selector": "feeds",
     "schema": 12,
     "source": "url",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "type": "json",
     "url": "https://api.thingspeak.com/channels/1047093/feeds.json?results=80000",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}