{
 "title": "VMWARE ESXI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DISPOSITIVO",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "DISPONIBILIDADE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": {
    "content": "<CENTER><img style=\"width:px;height:100px;vertical-align:middle;margin-bottom:0px;\" src=\"https://i.ibb.co/GvTxc7Q/VMware-SRM.png\"> "
   }
  },
  {
   "title": "ESXi Build",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "ESXi Build" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "VERSÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "ESXi Version" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CPU LOAD",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "CPU CORE #1 Utiization" },
     "itemTag": { "filter": "Application: CPU" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "FeeNas-Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "Volume - [Real Memory] TOTAL" },
     "itemTag": { "filter": "Application: Memory" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Data-Store-1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/591349a6-3ca63eb8-55d9-001ec9b1de22] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/650439a1-acbea02e-e889-002219b5f8fc] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/5ca4e9dc-9bb41733-b62d-d09466ae0086] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/641aa7c1-e1338ddd-cae4-d4bed9f94d35] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/62c3261b-f71ef56e-a153-180373f63da6] TOTAL"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:138",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "Volume - [Real Memory] USED" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2817",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/591349a6-3ca63eb8-55d9-001ec9b1de22] USED"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2838",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/650439a1-acbea02e-e889-002219b5f8fc] USED"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2859",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/5ca4e9dc-9bb41733-b62d-d09466ae0086] USED"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2880",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/641aa7c1-e1338ddd-cae4-d4bed9f94d35] USED"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2901",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/62c3261b-f71ef56e-a153-180373f63da6] USED"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2922",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/591349a6-3ca63eb8-55d9-001ec9b1de22] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2943",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/650439a1-acbea02e-e889-002219b5f8fc] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2964",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/5ca4e9dc-9bb41733-b62d-d09466ae0086] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "$$hashKey": "object:2985",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/62c3261b-f71ef56e-a153-180373f63da6] TOTAL"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "Memory" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:3012",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ " " ],
       "text": "setAlias( )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "Volume - [/vmfs/volumes/641aa7c1-e1338ddd-cae4-d4bed9f94d35] TOTAL"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  { "title": "Status das VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "TOTAL DE VMS" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "TOTAL DE VMS UP" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "TOTAL DE VMS DOWN" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Application: VMPOWERSTATE" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:59",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "2- Status",
        " "
       ],
       "text": "replaceAlias(2- Status,  )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "/^(?!.*(WMDedicado|Lucas Soneca)).*/"
     },
     "itemTag": { "filter": "Application: VMPOWERSTATE" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 9, "y": 19 },
   "targets": [
    {
     "application": { "filter": "Application: VMSTATUS" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "/^(?!.*(WMDedicado|Lucas Soneca)).*/"
     },
     "itemTag": { "filter": "Application: VMSTATUS" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "/^(?!.*(WMDedicado|Lucas Soneca)).*/"
     },
     "itemTag": { "filter": "Application: VMCpu" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "Application: VMSO" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "/^(?!.*(WMDedicado|Lucas Soneca)).*/"
     },
     "itemTag": { "filter": "Application: VMSO" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Memoria Total",
   "type": "table",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": {
      "filter": "/^(?!.*(WMDedicado|Lucas Soneca)).*/"
     },
     "itemTag": { "filter": "Application: VMMemory" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TRÁFEGO DE INTERFACES",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:690",
       "added": false,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "$DISPOSITIVO:",
        " "
       ],
       "text": "replaceAlias($DISPOSITIVO:,  )"
      }
     ],
     "group": { "filter": "/.*/" },
     "host": { "filter": "$DISPOSITIVO" },
     "item": { "filter": "/.*/" },
     "itemTag": {
      "filter": "Application: Network interfaces"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}