{
 "title": "TV NOC 1",
 "tags": [
  "outros",
  "ZABBIX SERVER DASH"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP BMP" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "TechnoBox DNS" },
     "host": { "filter": "TechnoBox DNS-01-COLETAS" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": State code",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "BGP ",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "CCR1036 BGP Telefonia" },
     "item": { "filter": "/.*: State code/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "CDN" },
     "host": { "filter": "CDN GGC-1" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "CDN" },
     "host": { "filter": "CDN GGC-2" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP CHIADOR" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-CHIADOR" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:697",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP LEVY" ],
       "text": "setAlias(POP LEVY)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-LEVY-02" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:718",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP SIMÃO" ],
       "text": "setAlias(POP SIMÃO)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-06-SIMAO-PEREIRA" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:760",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP SANTANA" ],
       "text": "setAlias(POP SANTANA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-07-SANTANA" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:781",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP VILA" ],
       "text": "setAlias(POP VILA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-VILA" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:808",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP BMP" ],
       "text": "setAlias(POP BMP)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-BEMPOSTA" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP PARAÍBA" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBA - 04" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP ALBERTO TORRES" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-ALBERTO-TORRES" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP CPD TR" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP CPD TR-02" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": {
      "filter": "SW -MPLS-PE-TR CENTRO POP2 - 03"
     },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP PARAIBUNA" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBUNA-03" },
     "item": { "filter": "MPU Board 0: Temperature" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "TechnoBox DNS" },
     "host": { "filter": "TechnoBox DNS-02-COLETAS" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "BGP RKPI NicBR" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "Routinator BGP" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "Energia" },
     "host": {
      "filter": "ROUTER ENERGIA BMP CPD TR TELECOM"
     },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:138",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO BMP FIBRA 1 (ALTAREDE-Swap)"
       ],
       "text": "setAlias(CIRCUITO LACP BMP FIBRA 1 (ALTAREDE))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-BEMPOSTA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:159",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO TR / ALBERTO TORRES" ],
       "text": "setAlias(CIRCUITO LACP BMP FIBRA 2 (TR))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/19: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:453",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO ALBERTO TORRES / BMP" ],
       "text": "setAlias(CIRCUITO BMP / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-ALBERTO-TORRES" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:180",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TRÊS RIOS / LEVY" ],
       "text": "setAlias(TRÊS RIOS / LEVY)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/11: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO / LEVY X PARAIBUNA" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-LEVY-02" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/23: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:243",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO POP VILA FIBRA 1 - SENTIDO UPA"
       ],
       "text": "setAlias(CIRCUITO LACP MPLS SW-07 POP VILA (FIBRA 1 - Sentido Upa))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-VILA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/1: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:264",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO POP VILA (FIBRA 2 - PADRE SOLANO"
       ],
       "text": "setAlias(CIRCUITO LACP MPLS SW-07 POP VILA (FIBRA 2 - Padre Solano))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/13: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:348",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO CHIADOR / SANTANA" ],
       "text": "setAlias(CIRCUITO CHIADOR / SANTANA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-07-SANTANA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:369",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO VILA / CHIADOR" ],
       "text": "setAlias(CIRCUITO VILA / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-VILA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:390",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO SIMÃO PEREIRA / SANTANA "
       ],
       "text": "setAlias(CIRCUITO SANTANA / SIMÃO PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-07-SANTANA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/1: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:411",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 1"
       ],
       "text": "setAlias(CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 1)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/17: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:432",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO LACP CPD-CENTRO / PARAÍBA"
       ],
       "text": "setAlias(CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 2)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": {
      "filter": "SW -MPLS-PE-TR CENTRO POP2 - 03"
     },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/3: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:453",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO BMP / CHIADOR" ],
       "text": "setAlias(CIRCUITO BMP / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-CHIADOR" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO / PARAIBUNA X SIMÃO 2" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBUNA-03" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: RxPower"
     },
     "itemTag": {
      "filter": "Application: Transceiver Data Interface SL: XGigabitEthernet0/0/24"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO / LEVY X PARAIBUNA  F 2"
       ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-LEVY-02" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/22: RxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TRÊS RIOS 01 - TRÊS RIOS 02" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface 40GE0/0/4: RxPower Lane0"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO / PARAIBUNA X SIMÃO 1" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBUNA-03" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/23: RxPower"
     },
     "itemTag": {
      "filter": "Application: Transceiver Data Interface SL: XGigabitEthernet0/0/23"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 19, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:138",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO BMP FIBRA 1 (ALTAREDE-Swap)"
       ],
       "text": "setAlias(CIRCUITO LACP BMP FIBRA 1 (ALTAREDE))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:159",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO TR / ALBERTO TORRES" ],
       "text": "setAlias(CIRCUITO LACP BMP FIBRA 2 (TR))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/19: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:453",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO ALBERTO TORRES / BMP" ],
       "text": "setAlias(CIRCUITO BMP / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-ALBERTO-TORRES" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": {
      "filter": "Application: Transceiver Data Interface SL: XGigabitEthernet0/0/24"
     },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:180",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TRÊS RIOS / LEVY" ],
       "text": "setAlias(TRÊS RIOS / LEVY)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/11: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO / LEVY X PARAIBUNA" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-LEVY-02" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/23: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:243",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO POP VILA (FIBRA 1 - Sentido Upa)"
       ],
       "text": "setAlias(CIRCUITO LACP MPLS SW-07 POP VILA (FIBRA 1 - Sentido Upa))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-VILA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/1: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:264",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO POP VILA (FIBRA 2 - Padre Solano)"
       ],
       "text": "setAlias(CIRCUITO LACP MPLS SW-07 POP VILA (FIBRA 2 - Padre Solano))"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/13: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:348",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO CHIADOR / SANTANA" ],
       "text": "setAlias(CIRCUITO CHIADOR / SANTANA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-07-SANTANA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:369",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO VILA / CHIADOR" ],
       "text": "setAlias(CIRCUITO VILA / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-VILA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:390",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO SIMÃO PEREIRA / SANTANA "
       ],
       "text": "setAlias(CIRCUITO SANTANA / SIMÃO PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "MPLS-PE-07-SANTANA" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/1: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:411",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 1"
       ],
       "text": "setAlias(CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 1)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/17: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:432",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO LACP CPD-CENTRO / PARAÍBA"
       ],
       "text": "setAlias(CIRCUITO LACP TRÊS RIOS / PARAÍBA FIBRA 2)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": {
      "filter": "SW -MPLS-PE-TR CENTRO POP2 - 03"
     },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/3: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:453",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CIRCUITO BMP / CHIADOR" ],
       "text": "setAlias(CIRCUITO BMP / CHIADOR)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-CHIADOR" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:285",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "paraibuna x simao" ],
       "text": "setAlias(LINK DEDICADO ITANET)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBUNA-03" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/23: TxPower"
     },
     "itemTag": {
      "filter": "Application: Transceiver Data Interface SL: XGigabitEthernet0/0/23"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "CIRCUITO / LEVY X PARAIBUNA F 2"
       ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-LEVY-02" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:201",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "TRÊS RIOS 01 - TRÊS RIOS 02" ],
       "text": "setAlias(CIRCUITO / LEVY X S PEREIRA)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW - 6730 OLTS" },
     "item": {
      "filter": "Optical Module Interface 40GE0/0/4: TxPower Lane0"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "RX-POWER" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:285",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "paraibuna x simao f 2" ],
       "text": "setAlias(LINK DEDICADO ITANET)"
      }
     ],
     "group": { "filter": "SWITCH" },
     "host": { "filter": "SW -MPLS-PE-PARAIBUNA-03" },
     "item": {
      "filter": "Optical Module Interface XGigabitEthernet0/0/24: TxPower"
     },
     "itemTag": {
      "filter": "Application: Transceiver Data Interface SL: XGigabitEthernet0/0/24"
     },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Paraíba" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP PARAIBA HW" },
     "item": { "filter": "AC - Status de Entrada" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "S. Pereira" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP SIMAO PEREIRA" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Chiador" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ROUTERSPOP" },
     "host": { "filter": "ROUTER WIFI POP CHIADOR" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPD TR R.1" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP CPD TR RACK 1 HW" },
     "item": { "filter": "AC - Status de Entrada" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Levy" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Modo de operacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Santana" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ROUTERSPOP" },
     "host": { "filter": "ROUTER WIFI POP SANTANA" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Vila" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Modo de operacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "A. Torres" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ROUTERSPOP" },
     "host": { "filter": "ROUTER WIFI POP ALBERTO TORRES" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Paraibuna" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP PARAIBA HW" },
     "item": { "filter": "AC - Status de Entrada" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Bemposta" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP CPD BMP HW" },
     "item": { "filter": "AC - Status de Entrada" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "CPD TR R.2" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP CPD TR RACK 2 HW" },
     "item": { "filter": "AC - Status de Entrada" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "POP CENTRO 02" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "ROUTERSPOP" },
     "host": { "filter": "ROUTER WIFI POP CPD 02 CENTRO" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "Application: Status" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "PROBLEMS GERAIS",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 27 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "CGNATS" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PPPOE" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SERVIDOR" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "OLT" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "/.*/" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Nobreak" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "Application: Battery" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "VMWARE" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Telefonia" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:581",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LINK GGNET " ],
       "text": "setAlias(LINK GGNET )"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/3.1601(Link Operadora-02 GGNET (FIBRA VIADUTO VLAN 1601)): Operational status"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:602",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "LINK MEGANET - FIBRA 1 ROTA VIADUTO"
       ],
       "text": "setAlias(LINK K2 - FIBRA 1 ROTA VIADUTO)"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/1(Link Operadora-02 K2 LACP Fibra TrTelecom (Rua da Viaduto) Eth-Trunk 843): Operational status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:623",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [
        "LINK MEGANET - FIBRA 2 ROTA PROSCAN"
       ],
       "text": "setAlias(LINK K2 - FIBRA 2 ROTA PROSCAN)"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/2(Link Operadora-01 K2 LACP Fibra TrTelecom (Rua da ProsCan) Eth-Trunk 843): Operational status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:60",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LINK GGNET " ],
       "text": "setAlias(LINK GGNET )"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/3.1601(Link Operadora-02 GGNET (FIBRA VIADUTO VLAN 1601)): Operational status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:81",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LINK K2 - FIBRA 1 ROTA VIADUTO" ],
       "text": "setAlias(LINK K2 - FIBRA 1 ROTA VIADUTO)"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/1(Link Operadora-02 K2 LACP Fibra TrTelecom (Rua da Viaduto) Eth-Trunk 843): Operational status"
     },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "$$hashKey": "object:102",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "LINK K2 - FIBRA 2 ROTA PROSCAN" ],
       "text": "setAlias(LINK K2 - FIBRA 2 ROTA PROSCAN)"
      }
     ],
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "Interface 40GE0/3/2(Link Operadora-01 K2 LACP Fibra TrTelecom (Rua da ProsCan) Eth-Trunk 843): Operational status"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 31 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "LINKS DEDICADOS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "stat",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": ICMP ping",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "DEDICADO" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "/.*ICMP ping/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "application": { "filter": "SIPSTATUS" },
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_LC1" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "SIPSTATUS" },
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_LC2" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "SIPSTATUS" },
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_LD1" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "SIPSTATUS" },
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_LD2" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "SIPSTATUS" },
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_TR1" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "SIPSTATUS" },
     "evaltype": "0",
     "group": { "filter": "Telefonia" },
     "host": { "filter": "E1-Aligera" },
     "item": { "filter": "Status OI_PETRO_TR2" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  { "title": "FONTES RETIFICADORAS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 58 },
   "options": {
    "content": "<div style=\"\n  display: flex; \n  align-items: center; \n  justify-content: center;\n  font-size: 25px; \n  font-weight: 700; \n  background-color: #1e2d79; \n  border-radius: 10px; \n  text-align: center;\n  padding: 10px;\n  gap: 20px;\n\">\n  <img \n    src=\"https://www.trtelecom.net/7c29480d-3cf8-4258-9b39-e32dfe42a7df.png\" \n    width=\"70px\"\n    style=\"flex-shrink: 0;\"\n  />\n  <p style=\"margin: 0;\">Fonte Nobreak Retificadora JFA - Levy Gasparian\n</p>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 58 },
   "options": {
    "content": "<div style=\"\n  display: flex; \n  align-items: center; \n  justify-content: center;\n  font-size: 25px; \n  font-weight: 700; \n  background-color: #1e2d79; \n  border-radius: 10px; \n  text-align: center;\n  padding: 10px;\n  gap: 20px;\n\">\n  <img \n    src=\"https://www.trtelecom.net/7c29480d-3cf8-4258-9b39-e32dfe42a7df.png\" \n    width=\"70px\"\n    style=\"flex-shrink: 0;\"\n  />\n  <p style=\"margin: 0;\">Fonte Nobreak Retificadora JFA - Vila Isabel</p>\n</div>\n"
   }
  },
  {
   "title": "TENSÃO DA BATERIA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TENSÃO DE SAIDA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao de saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TEMPERATURA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Temperatura Interna" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "MODO DE OPERAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Modo de operacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "FONTE DE ALIMENTAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Fonte Alimentacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "STATUS DE OPERAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "SNMP availability" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TENSÃO DA BATERIA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TENSÃO DE SAIDA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao de saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TEMPERATURA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Temperatura Interna" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "MODO DE OPERAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Modo de operacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "FONTE DE ALIMENTAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Fonte Alimentacao" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "STATUS DE OPERAÇÃO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "SNMP availability" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CARGA DA BATERIA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Carga Bateria" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TENSÃO REDE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao Rede" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "Application: Uptime" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CARGA DA BATERIA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Carga Bateria" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "TENSÃO REDE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "fonte" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao Rede" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Uptime" },
     "itemTag": { "filter": "Application: Uptime" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Tensão da rede (VAC)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao Rede" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tensão da rede (VAC)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao Rede" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Corrente de saída",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Corrente Saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tensão de saída",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 72 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao de saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Corrente de saída",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Corrente Saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tensão de saída",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 72 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao de saida" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Corrente no Carregador",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Corrente Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tensão do carregador",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 76 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP LEVY JFA" },
     "item": { "filter": "Tensao Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Corrente no Carregador",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Corrente Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Tensão do carregador",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 76 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "ENERGIA" },
     "host": { "filter": "ENERGIA POP VILA ISABEL JFA" },
     "item": { "filter": "Tensao Carregador" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "MBPS IN",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")  / 1000000 FROM \"total\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND \"app\" =~ /^fastnetmon$/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}