{
 "title": "Dashboard - Proxmox",
 "description": "\n",
 "tags": [ "CPT-02 TR TELECOM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "VM",
    "label": "Maquina",
    "query": {}
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"\r\n    width: 2000px;\r\n    height: 85px;\r\n    background-image: url('https://images7.alphacoders.com/134/1344394.png');\r\n    background-size: cover;\r\n    background-position: center;\r\n    display: flex;\r\n    justify-content: center;\r\n    align-items: center;\r\n\">\r\n    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Logo_Proxmox.svg/2560px-Logo_Proxmox.svg.png\" alt=\"Logo Proxmox\" style=\"height: 40px;\">\r\n</div>\r\n"
   }
  },
  {
   "title": "Ping Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": ICMP ping",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": ICMP response time",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP Loss",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": ICMP loss",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">JOBS Main Cluster</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*CPU, usage/" },
     "itemTag": { "filter": "/node:/" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/Node(.*): Uptime/" },
     "itemTag": { "filter": "/node:/" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*Memory, total/" },
     "itemTag": { "filter": "/node:/" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*Memory, used/" },
     "itemTag": { "filter": "/node:/" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 18 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": API service status",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "API service status" },
     "itemTag": { "filter": "component: system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": true
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": Size",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "Storage ",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "Storage [PVE-01/DATA-01]: Size" },
     "itemTag": { "filter": "node: PVE-01" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": Size",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "Storage ",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "Storage [PVE-02/DATA-01]: Size" },
     "itemTag": { "filter": "node: PVE-02" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": Size",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "Storage",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": {
      "filter": "Storage [PVE-03-PBS/local-lvm]: Size"
     },
     "itemTag": { "filter": "node: PVE-03-PBS" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "Storage [PVE-01/DATA-01]: Used" },
     "itemTag": { "filter": "node: PVE-01" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "Storage [PVE-02/DATA-01]: Used" },
     "itemTag": { "filter": "node: PVE-02" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": {
      "filter": "Storage [PVE-03-PBS/local-lvm]: Used"
     },
     "itemTag": { "filter": "node: PVE-03-PBS" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Consumo CPU Histórico",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": {
      "filter": "/^Node \\[.*?\\]: CPU, usage$/i"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 35 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n    color: #0000AA; /* Cor do texto */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">NETWORK IN - Migration</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 35 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n    color: #0000AA; /* Cor do texto */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">NETWORK OUT - Migration</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Entrada na Interface Ethernet1/50(Servidor HP-DL360 Proxmox IP 172.16.20.11/24 Init interface VLNs)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Entrada na Interface Ethernet1/20(Link Storage PVE-01 IP 192.168.100.2/24  )"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Entrada na Interface Ethernet1/21(Link Storage PVE-02 IP 192.168.100.3/24  )"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": {
      "filter": "CPD-02 RACK-02 SG 2404MR GERENCIA"
     },
     "item": {
      "filter": "Tráfego de Entrada na Interface Porta 24 - SWCore-Rack-1"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "Cisco N3k CPD-02 Servidores" },
     "item": {
      "filter": "Trafego de Entrada na Interface Ethernet1/4(Servidor DELL1950 PVE-ProxMox)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/5(Servidor DELL R230 ProxMox / PBS 172.16.20.4/24 VLAN 101 Link BG)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/17(Link BGP Servidor dell R630-07)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/19(Link BGP Servidor dell R630-06)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/6(Servidor DELL 2950 PVE Proxmox 172.16.20.5/24 VLAN 101 Link BGP)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/4(Servidor DELL 1950 PVE Proxmox 172.16.20.6/24 VLAN 101 Link BGP)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "SWITCH" },
     "host": { "filter": "N3k Cisco CPD-02 Data Center" },
     "item": {
      "filter": "Trafego de Saida na Interface Ethernet1/27(Servidor DELL R610-01 PVE Proxmox 172.16.20.7/24 VLAN 101 Link B)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/Pull PBS .*/" },
     "item": {
      "filter": "Interface LinkBGP(): Bits received"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "/Pull PBS .*/" },
     "item": { "filter": "Interface LinkBGP(): Bits sent" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">JOBS VMs</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "table",
   "gridPos": { "h": 25, "w": 9, "x": 2, "y": 53 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "(qemu",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      },
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        ": CPU usage",
        " "
       ],
       "text": "replaceAlias(/(.*)/, $1)"
      }
     ],
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*CPU usage/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 25, "w": 3, "x": 11, "y": 53 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*CPU usage/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 25, "w": 3, "x": 14, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/.*Uptime/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 25, "w": 3, "x": 17, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/Memory total/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 25, "w": 3, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/Memory usage/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Histórico CPU - VMS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/CPU usage/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 83 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n    color: #0000AA; /* Cor do texto */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">NETWORK IN - VMS</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 83 },
   "options": {
    "content": "<div style=\"\r\n    font-size: 32px;\r\n    text-align: center;\r\n    font-family: 'Arial Black', sans-serif;\r\n    border-radius: 0px 100px 0px 100px;\r\n    background-image: url('https://minio.trtelecom.net/api/v1/buckets/dedicados/objects/download?preview=true&prefix=3d-render-abstract-background-with-cyber-particles-design.jpg&version_id=41264e09-ed2a-486e-b5d1-bd077f85b6b7');\r\n    background-size: cover; /* Ajusta a imagem para cobrir toda a área do div */\r\n    background-position: center; /* Centraliza a imagem de fundo */\r\n    color: #0000AA; /* Cor do texto */\r\n\">\r\n    <span style=\"font-family: Arial; color: #0000AA;\">NETWORK OUT - VMS</span>\r\n</div>\r\n"
   }
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/Incoming data, rate/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "PROXMOX" },
     "host": { "filter": "$Node" },
     "item": { "filter": "/Outgoing data, rate/" },
     "itemTag": { "filter": "$VM" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}