{
 "title": "Fastnetmon",
 "description": "Fastnetmon",
 "tags": [ "fast" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Datacenter",
    "query": "SHOW TAG VALUES WITH KEY = \"app\""
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "DESCONHECIDO/10.7.7.2 - Status do peer"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "DESCONHECIDO/10.7.7.2 - Prefixo recebidos"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "BGP" },
     "host": { "filter": "ROUTER-BGP" },
     "item": {
      "filter": "DESCONHECIDO/10.7.7.2 - Tempo estabelecido"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "MBPS IN",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")  / 1000000 FROM \"total\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "PPS IN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE (\"direction\" = 'incoming' AND \"resource\" = 'pps'  AND \"app\" =~ /^$Datacenter$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "PPS OUT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE (\"direction\" = 'outgoing' AND \"resource\" = 'pps' AND \"app\" =~ /^$Datacenter$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "MBPS OUT",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")  / 1000000 FROM \"total\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/ AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Top Outgoing ( Traffc ) > 40 Mbps",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"hosts\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/ AND value > 40000000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Incoming ( Traffc ) > 20 Mbps",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"hosts\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/  AND value > 20000000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Outgoing ( Packets ) > 3,8 kpps",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"hosts\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'pps' AND \"app\" =~ /^$Datacenter$/  AND value > 3800 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Incoming ( Packets ) > 2,3 kpps",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"hosts\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'pps' AND \"app\" =~ /^$Datacenter$/  AND value > 2300 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Incoming By Subnet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"networks\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/ AND value > 1000000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top OutGoing By Subnet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"networks\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'bps' AND \"app\" =~ /^$Datacenter$/ AND value > 1000000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Incoming By Subnet ( Packets )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"networks\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'pps' AND \"app\" =~ /^$Datacenter$/ AND value > 1000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  },
  {
   "title": "Top Outgoing By Subnet ( Packets )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"networks\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'pps' AND \"app\" =~ /^$Datacenter$/ AND value > 1000 AND $timeFilter GROUP BY time($__interval), cidr fill(previous)"
    }
   ]
  }
 ]
}