{
 "title": "Fastnetmon PAINEL GERAL",
 "tags": [ "fast" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Máquina Fastnetmon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Maquina Host Fastnetmon" },
     "item": { "filter": "Load average (1m avg)" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Maquina Host Fastnetmon" },
     "item": { "filter": "Zabbix agent availability" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Maquina Host Fastnetmon" },
     "item": { "filter": "System uptime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Problems List",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "evaltype": "0",
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Maquina Host Fastnetmon" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Filesystem /" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "Maquina Host Fastnetmon" },
     "item": { "filter": "/: Space utilization" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Banco de dados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MBPS IN",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")  / 1000000 FROM \"total\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "PPS IN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction::tag", "operator": "=", "value": "incoming" },
      { "condition": "AND", "key": "resource::tag", "operator": "=", "value": "pps" }
     ]
    }
   ]
  },
  {
   "title": "PPS OUT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "direction::tag", "operator": "=", "value": "outgoing" },
      { "condition": "AND", "key": "resource::tag", "operator": "=", "value": "pps" }
     ]
    }
   ]
  },
  {
   "title": "MBPS OUT",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"value\")  / 1000000 FROM \"total\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'bps' AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'bps' AND $timeFilter GROUP BY time($__interval) fill(previous)"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'bps' AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  },
  {
   "title": "PACKETS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE \"direction\" = 'incoming' AND \"resource\" = 'pps' AND $timeFilter GROUP BY time($interval) fill(previous)"
    },
    {
     "query": "SELECT mean(\"value\") FROM \"total\" WHERE \"direction\" = 'outgoing' AND \"resource\" = 'pps' AND $timeFilter GROUP BY time($__interval) fill(previous)"
    }
   ]
  }
 ]
}